"""
Django settings for tests project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^bd*t%vv&*3!b=_2%qtzh@9tga3by6t#20-&2vhrkcc_vplmj^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'musombi_notifications'
]


FCM_DJANGO_SETTINGS = { 
    "FCM_SERVER_KEY": "AAAARCjU2bU:APA91bGr1yQ-dmpHLi2s3XOeO8D1camvzezU8l3ou5eEo2EM-ZAqZqbpuveKQPZcRE1Dj6cEuVeel5Atyo_Io1qqgugn_kOKA8uETkOLKiPdMqm9FI_C90ZhdRZ0saD17LWdYKcGhlBJ",
    "ONE_DEVICE_PER_USER": True,
    "DELETE_INACTIVE_DEVICES": True, 
 }

FIREBASE_CONFIG = '{"type": "service_account",    "project_id": "push-b573a",    "private_key_id": "b6dde4032b8b03e0cc09f3cfadeb6c5a47625259",    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDT5MOriFE54BYM\ndWiAaSODiGc5z7O5ISrDVE6pop5NqBtSUkc+/Deehvdcxyv7ktymvNBG8l6En4m8\nLH1QojTezkz3EWDdnrRBYQtPJktBN6cPx+APRtce9OoRHcebtIStj+/lCKRyVeA/\nxjTgcs5J2vUfh/y8sKdJy/K0juDHRVCo1k0xW/fsKk90k4OHBYwpQMkK8N00fCyx\n0mfc+qy02/g1vDXgK80OXurKOXYSOtfbzzXke8vi/qcKrhjLW6guPGqGepaYGgF2\nq0ossPX4tuVjTRmcjZCb4foO74VfmIqBsQQ0K/1kFlmXxRGyztjp3klrbFDTP+nE\n3j/zN8+DAgMBAAECggEAKac3u7mBViIx02MlFtEUNSAUQq4Mw2C8ukcRa5FXEybv\nsAASl1QXTudzKt7QS5T0ISbOvpOYdvOxrLcGL1qjkAT35j2ZUBeJkayU/4skkf5x\nrc15wycG1MQKWzECcx5KUqAP5XMMeJlfCspYzKJk4OnU88zUpvcG+5/G5y2LDEC9\nAWkAA/iOoiG2pRXYoyhI/YmMQ066uzgzjIuuXBUlLLzRw/FUoSvTLTygv1OBYUid\nZyid3ymocxGWrbOO+G1XSV/KsWldtx3FIFqZUHTSzeeZ7nKrH5+rZrorqVp9nX9F\n615lyG0b568vinXKIaCMriow2RLZOW8D8KIxcuZJgQKBgQD/uLg2IC4PXYmGq6eV\nKqbLHzLTFHkmNEpQ9bq8+yW/5sxZZmPrHaKDmm8K3ymQyDx1sgGJyMSU76Or9eU0\nkPjPy0YSLwhaYiTPtwCOSxyttS5xaXCQVaXBaX0fHZv5QbLDj/0+Ve0/I2TK5SOQ\njqge6HrP7E19y6HcyLAnby7YQQKBgQDUH9P7bUpkQt9SwRUmPQjteYVe2HZc4tiu\nZNBU+99uhq8Yn/NGjp+x1bT6FuSQAZpq/Zb3Z4iQnVow4vF0fi4nFPyA+Vrsf33D\nj4tiQt2aBOQfNGjqH4ZmhxLMr0WJ7mNLfeghYNcl9t7W22FJ/ZFeceG3OyCbWF50\no9SOAxOWwwKBgGtmpI+vAklXyrvx+kdvC3CCIPGARsWh7piELDLU9GzdvXPKyipk\nXu4Q/ZQ+WBHD14jDA1xgIxg+cap2cxaZ0LZNNJfMgyCa2cUXojchGuFmGCRv2WP1\nZNGPwYpBAFI2oqL6Ja15n1QGRH3msQI0uC2LDJGpOH6d+NRmwX0+eBlBAoGAXO60\nyGpRNSu2+2JsCZyj1KZwr+TVtkwL8htoylKuyJVpELjCtB64CAlAiHCPIigRpt4C\nzdEmG3VUliZW8lp1jdm75iVYmFQinRK+VgZFX7zU1Hb5n9i/4Rs8OUBwjsVJ60D1\n+embWJ6XcjoanXfhwCbUZJoa5vQILcG41Z6zblECgYEAr8MeHEsOe7pkqevcEtkZ\njV4QgEoszm5CW1ZcndwO8jC0VPzPOGodjIBUBNcBZ+az0bQ3BgWas/PTA20jTfPm\nVvsGkcIgRYQyZIsJD+1Lw7NDneoRlo8qpa5RFkBCiHlYF5MTTxOAwArtJFebEcJS\ngAdYIUdF361q3AehI8ffr9U=\n-----END PRIVATE KEY-----\n",   "client_email": "firebase-adminsdk-t3y1i@push-b573a.iam.gserviceaccount.com",    "client_id": "108137574074260624352",    "auth_uri": "https://accounts.google.com/o/oauth2/auth",    "token_uri": "https://accounts.google.com/o/oauth2/token",    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-t3y1i%40push-b573a.iam.gserviceaccount.com"}'

FIREBASE_DATABASE_URL = "https://push-b573a.firebaseio.com"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tests.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tests.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'